[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
itertools = "0.10.3"
lazy_static = "1.4.0"
rustc-hash = "1.1.0"
bit-vec = "0.6.3"
